[build]
  base = "react-website"  # Ensure Netlify starts in the correct directory
  command = "npm run build"
  publish = "react-website/dist"  # Change to "dist" because Vite builds here

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
