[build]
  command = "npm run build"
  publish = "dist"  # Corrected from "/build" to "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
